# Generated by Django 4.1.1 on 2022-10-20 20:59

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_eventcategory_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={}),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='code',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
