# Generated by Django 4.1.1 on 2022-10-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userprofile_alt_mobile_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='alt_mobile',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
