# Generated by Django 4.1.1 on 2022-10-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_userprofile_alt_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='alt_mobile',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
