# Generated by Django 4.1.1 on 2022-10-21 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_event_category_alter_event_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
