# Generated by Django 4.1.1 on 2022-10-21 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_event_created_date_alter_event_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='managers/'),
            preserve_default=False,
        ),
    ]
