# Generated by Django 4.1.1 on 2022-10-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_foodcategory_foodproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='order',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
