# Generated by Django 4.1.1 on 2022-10-24 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_foodproducts_category_alter_foodproducts_pair_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodproducts',
            name='paircat',
        ),
        migrations.AlterField(
            model_name='foodproducts',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.foodcategory'),
        ),
        migrations.AlterField(
            model_name='foodproducts',
            name='pair',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.foodproducts'),
        ),
    ]
