# Generated by Django 4.1.1 on 2022-10-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_foodproducts_paircat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodproducts',
            name='pair',
        ),
    ]
