# Generated by Django 4.1.1 on 2022-10-24 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_foodproducts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproducts',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.foodcategory'),
        ),
    ]
