# Generated by Django 4.1.1 on 2022-10-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_foodproducts_pair'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodproducts',
            old_name='pair',
            new_name='pair1',
        ),
    ]
