# Generated by Django 4.1.1 on 2022-10-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_pair_foodproducts_pair1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodproducts',
            old_name='pair1',
            new_name='pair',
        ),
    ]
