# Generated by Django 4.1.1 on 2022-10-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_pair1_foodproducts_pair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodproducts',
            name='pair',
        ),
    ]
