# Generated by Django 4.1.1 on 2022-10-24 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_foodproducts_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproducts3',
            name='paircat',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_paircat', to='main.foodcategory'),
        ),
    ]
