# Generated by Django 4.1.1 on 2022-10-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_foodproducts3_paircat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodproducts3',
            name='paircat',
        ),
    ]
