# Generated by Django 4.1.1 on 2022-10-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_foodproducts3_paircat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodProducts3',
        ),
    ]
