# Generated by Django 4.1.1 on 2022-10-24 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_delete_foodproducts3'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodProducts1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('image', models.ImageField(default='0000000', upload_to='Catering/products/')),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.foodcategory')),
                ('pair', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.foodproducts1')),
                ('paircat', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='_pairedcategory', to='main.foodcategory')),
            ],
        ),
    ]
