# Generated by Django 4.1.1 on 2022-10-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_foodproducts_paircategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodProducts1',
        ),
    ]
