# Generated by Django 4.1.1 on 2022-10-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_foodorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='status',
            field=models.CharField(default='Processing', max_length=10),
        ),
    ]
