# Generated by Django 4.1.1 on 2022-10-26 08:59

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_foodorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=mapbox_location_field.models.LocationField(default=(76.361736, 10.009277), map_attrs={}),
        ),
    ]
