# Generated by Django 4.1.1 on 2022-10-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_event_status_alter_userprofile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
