# Generated by Django 4.1.1 on 2022-10-31 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_event_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcart',
            name='pairevent',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.event'),
        ),
    ]
