# Generated by Django 4.1.1 on 2022-10-31 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_remove_foodcart_pairevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='menuCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=4)),
                ('price', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.foodproducts')),
            ],
        ),
    ]
