# Generated by Django 4.1.1 on 2022-10-31 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_menucart_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='menucart',
            name='quantity',
        ),
    ]
